@startuml

skinparam entity {
    BackgroundColor #F9F9F9
    BorderColor #005DAA
}

entity "Mahasiswa" as Mahasiswa {
    + NIM : String <<PK>>
    + Nama Mhs : String
}

entity "Mata Kuliah" as MataKuliah {
    + KD MK : String <<PK>>
    + Nama MK : String
}

entity "Dosen" as Dosen {
    + No Dosen : String <<PK>>
    + Nama Dosen : String
}

entity "Nilai" as Nilai {
    + NIM : String <<FK>>
    + KD MK : String <<FK>>
    + No Dosen : String <<FK>>
    + Nilai : String
}

Mahasiswa ||--o{ Nilai : "Mendapatkan"
MataKuliah ||--o{ Nilai : "Diajarkan"
Dosen ||--o{ MataKuliah : "Mengajar"


note right of Mahasiswa
  "1. 12345 - Ali\n
   2. 12346 - Darwin\n
   3. 12349 - Siti"
end note


note right of MataKuliah
  "1. TI-001 - Algoritma Pemrograman\n
   2. TI-101 - Basis Data"
end note

note right of Dosen
  "1. 771 - Dian\n
   2. 773 - Elias"
end note


note right of Nilai
  "1. 12345, TI-001, 771, A
   2. 12345, TI-101, 773, A
   3. 12346, TI-001, 771, B
   4. 12349, TI-001, 771, A"
end note

@enduml
